queue_rules:
- name: vm3-json-largeint-261007
  merge_method: fast-forward
  batch_size: 1
  queue_conditions:
  - base = vm3-jsonbig-base-261007
  merge_conditions:
  - check-success = vm3-jsonbig-never-check
- name: vm3-jsondup-261007
  merge_method: merge-batch
  batch_size: 2
  queue_conditions:
  - base = vm3-jsondup-base-261007
  merge_conditions:
  - check-success = vm3-jsondup-never-check
conflict_resolvers:
- paths:
  - vm3-largeint-policy.json
  strategy: json
- paths:
  - vm3-dupkey-policy.json
  strategy: json
